# Generated by Django 3.1.6 on 2021-02-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='target',
            field=models.SlugField(max_length=24),
        ),
    ]
